version: "3.1"

services:
  db:
    image: postgres
    container_name: my-postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
